### PR TITLE
Implemented next js, tailwind css and typescript

### PR DESCRIPTION
**Pull request by aniketk13**

### CODE REVIEW

**Comment by Souvikns** [comment]
@aniketk13 have you also committed `node_modules`?

**Comment by aniketk13** [comment]
> 

Shall I put it in git ignore?

**Comment by Souvikns** [comment]
Yeah, you should, also add the `.next` folder.

**Comment by aniketk13** [comment]
> Yeah, you should, also add the `.next` folder.

Alright

**Pull request closed without merging**
